# Generated by Django 5.0.2 on 2024-04-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='merina.jpeg', upload_to='blog/profile_pics'),
        ),
    ]
