# Generated by Django 5.0.2 on 2024-04-21 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_resume_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.resume'),
        ),
    ]
