# Generated by Django 5.0.2 on 2024-05-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.CharField(default='No information', max_length=1000),
        ),
        migrations.AddField(
            model_name='resume',
            name='work',
            field=models.CharField(default='No information', max_length=1000),
        ),
    ]
